use_frameworks!

platform :ios, '10.0'

target 'GinguareCocoapodsLibrary_Example' do
  pod 'GinguareCocoapodsLibrary', :path => '../'

  target 'GinguareCocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
